### PR TITLE
Bump to 0.27.3

### PR DESCRIPTION
**Pull request by arusa**
And make compatible until <0.28

### CODE REVIEW

**Comment by arusa** [comment]
This also fixes the 0.27 issue with UserExportSerializer: #11

**Comment by paulinebessoles** [comment]
Awesome @arusa ! Do you think you could also add some tests to this 0.27 version?
@Quentinchampenois wrote some for the 0.26 version that could be reused I think!
https://github.com/PopulateTools/decidim-module-extra_user_fields/tree/release/0.26-stable/spec

**Comment by paulinebessoles** [comment]
@ferblape do you think this PR could be merged soon?
I can try to add and update tests in another PR if that works for you!

**Comment by ferblape** [comment]
Totally!

**Pull request merged**
