### PR TITLE
Adapt to 0.28 release and phone number enhancements

### PR DESCRIPTION
**Pull request by Crashillo**
Closes https://github.com/PopulateTools/issues/issues/1926

- Refactor views to fit for 0.28 release (redesign)
- Use an specific telephone field for forms, in order to validate, via pattern, whether the phone number is valid or not. Such pattern can be edited by admins.
- Allows admins also to edit the placeholder text which will appear in the users registration and edit account forms
- Updates tests to 0.28 and adds new examples to check the phone number validation

Default pattern for spanish phonenumber: `^(\\+34)?[0-9 ]{9,12}$`

Check the feature at https://decidim-redesign.populate.tools/admin/organization/edit

#### Pending
- [x] Persist to database the pattern chosen in the admin site
- [x] Place backend code properly
- [x] Add icon for the admin menu (engine.rb)

#### Screenshots
Admin:
imagen

Export Users feature:
Screenshot from 2024-04-17 16-01-21

Profile:
imagen

Register:
imagen

### CODE REVIEW

**Comment by furilo** [comment]
What patterns are allowed?
How are we explaining/documenting them?

**Comment by furilo** [comment]
Think from the admin perspective that is going to configure the field...

**Comment by Crashillo** [comment]
In that case, we can add _help texts_ to the _phone number pattern_ and _phone number placeholder_... althoughI think the fields are self-explanatory enough
imagen

**Review by aramollis — CHANGES_REQUESTED** [review]
https://www.loom.com/share/4a5500b5f1df4c9f9f392ff657a74550
1. Only phone field has some kind of validation (you can define future date for birthday, and any character in CP...)
2. In the admin config isn't easy to understand the validation rule `^(\+34)?[0-9 ]{9,12}$`. This rule allow 3 extra digits +34999111222000 and numbers like 123456789 that are evident wrong spanish phone numbers
3. If you deactivate extra user fields (not each field) the new fields disappear from signup form but not in edit profile form. For the profile you need to deactivate each field. https://www.loom.com/share/f210af6caa88440dbbac5e511842d275


I suggest at least
- [x] Improve validation phone rule to allow real phone numbers 
- [x] Add this explanation in the admin config: Copia esta expresión "regex"  `^(\+34)?[0-9 ]{9,12}$` para validar este formato de teléfono +34999111222
- [ ] When deactivate extra user fields from admin config hide fields also from profile form

**Comment by furilo** [comment]
Aram define the various formats for the phone so the regex can be adjusted.

**Comment by aramollis** [comment]
> Aram define the various formats for the phone so the regex can be adjusted.

I'm not sure about. I found [Plan nacional numeración 2021-02 Mnisterio Economía](https://avancedigital.mineco.gob.es/es-ES/Servicios/Numeracion/Documents/Guia_Numeracion.pdf)
I understand we should allow to start:
- `0034` or `+34` or ¿nothing?
- First number should be only `9|8` for "fijos" and `6|7` for "móviles"
- Second number couldn't be `0` they are reserved for paid services (Exception for `70` that are personal redirections to fijo/móvil)

Posible [example](https://www.codigonexo.com/blog/programacion/php/expresion-regular-para-numeros-de-telefono/) of rules for fijo & móvil

I should ask client to validate this allowed examples?
- +34 9## ### ###
- +34 8## ### ###
- +34 6## ### ###
- +34 7## ### ###

- 9## ### ###
- 8## ### ###
- 6## ### ###
- 7## ### ###

And not allowed
- +34 90*
- +34 80*
- +34 60*
- 90*
- 80*
- 60*
- 1-5*
- 0*
- Less than 9 digit numbers

**Comment by furilo** [comment]
I would go with the example of the URL:

`(\+34|0034|34)?[ -]*(6|7)[ -]*([0-9][ -]*){8}`

completing it so a phone can start by 8 and 9

**Comment by entantoencuanto** [comment]
I have added a small change in the admin form to hide the phone number pattern and placeholder fields if the attribute is deactivated and hide the options for each field if the feature is globally disabled

**Review by aramollis — APPROVED** [review]
Now phone number validation works ok! 👏

**Pull request merged**
