### PR TITLE
Add tests to 0.27

### PR DESCRIPTION
**Pull request by paulinebessoles**
This pull request aims to:

- [x] add tests to the 0.27 version of the module. 
- [x] implement location and phone number fields to make them configurable

### CODE REVIEW

**Comment by paulinebessoles** [comment]
@ferblape could you please approve the workflow to run so I can check nothing fails in the ci? 😁

**Comment by furilo** [comment]
Done!

**Comment by paulinebessoles** [comment]
@furilo sorry, could you run it again? 😊

**Comment by furilo** [comment]
https://github.com/PopulateTools/decidim-module-extra_user_fields/actions/runs/6025862629/job/16347687383?pr=17 ? ;)

**Comment by paulinebessoles** [comment]
@furilo really hope it's the last time!

**Comment by furilo** [comment]
The PR is looking great! Thanks a lot. Would it make sense to complete the readme? Our version was quite basic...

**Comment by paulinebessoles** [comment]
@furilo I added some extra indications in the README, please tell me if you want some more infos! 

Furthermore, I started testing one last time in local and saw that some fields are not displayed event though they should be so please do not merge this PR (or convert to draft) for now 😔

**Comment by paulinebessoles** [comment]
@furilo @ferblape Now the PR is finalized! 

Please tell me if you have any change request 😁

**Comment by ferblape** [comment]
Hi @paulinebessoles thanks for the PR it's fantastic and I'm going to merge it right now.

After that we are going to:

- fix the branches mess, so `extra-fields-0-27` branch will go to master
- then, in master we are going to update the README with much more detail. Your improvements are great but it was in our plate to do a much complete manual
- third, we'll release the stable 0.27 branch which you could link in your Gemfiles

**Pull request merged**
